### ISSUE TITLE
Please replace urlopen with requests

### ISSUE THREAD

**Issue by yakovkeselman** [weblyzard/inscriptis#17]
The following command does not work: ./scripts/inscript.py https://azuqua.workable.com/j/D782546DD0
Stack trace is below. After replacing the offending line with "html_content = (requests.get(args.input)).text" it worked fine. Thanks.

Traceback (most recent call last):
  File "./scripts/inscript.py", line 54, in <module>
    http_client = urlopen(args.input)
  File "/home/yakov/anaconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/yakov/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/yakov/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/yakov/anaconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/yakov/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/yakov/anaconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by AlbertWeichselbraun** [comment]
thank you - this has been addressed in [0.0.3.8]( https://github.com/weblyzard/inscriptis/releases/tag/0.0.3.8) and in the master branch.
